name: earthquake-feature-pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '11 11 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'
          
      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Running Feature pipeline
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          CLEANED_CSV_FILE_NAME: ${{secrets.CLEANED_CSV_FILE_NAME}}
          CLEANED_S3_BUCKET_NAME: ${{secrets.CLEANED_S3_BUCKET_NAME}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_KEY: ${{secrets.AWS_KEY}}
          AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
        run: |
          python3 ./src/earthquake-feature-pipeline.py

      - name: Running training pipeline
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          CLEANED_CSV_FILE_NAME: ${{secrets.CLEANED_CSV_FILE_NAME}}
          CLEANED_S3_BUCKET_NAME: ${{secrets.CLEANED_S3_BUCKET_NAME}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_KEY: ${{secrets.AWS_KEY}}
          AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
        run: |
          python3 ./src/earthquake-training-pipeline.py
  

      - name: Running Inference pipeline
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          CLEANED_CSV_FILE_NAME: ${{secrets.CLEANED_CSV_FILE_NAME}}
          CLEANED_S3_BUCKET_NAME: ${{secrets.CLEANED_S3_BUCKET_NAME}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_KEY: ${{secrets.AWS_KEY}}
          AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
        run: |
          python3 ./src/earthquake-inference-endpoint.py
